<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExtraProductsSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $products = [
            // Filtre (category_id = 1) — 4 yeni ürün
            [
                'category_id'    => 1,
                'sku'            => 'FLT-2201',
                'barcode'        => '8690001122011',
                'name'           => 'İletim Yağı Filtresi',
                'stock_quantity' => 45,
                'store_stock'    => 10,
                'minimum_stock'  => 5,
                'purchase_price' => 85.00,
                'sale_price'     => 145.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 1,
                'sku'            => 'FLT-2202',
                'barcode'        => '8690001122022',
                'name'           => 'Dizel Mazot Filtresi',
                'stock_quantity' => 38,
                'store_stock'    => 8,
                'minimum_stock'  => 5,
                'purchase_price' => 110.00,
                'sale_price'     => 185.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 1,
                'sku'            => 'FLT-2203',
                'barcode'        => '8690001122033',
                'name'           => 'Şasi Hava Kurutucusu',
                'stock_quantity' => 20,
                'store_stock'    => 5,
                'minimum_stock'  => 3,
                'purchase_price' => 220.00,
                'sale_price'     => 375.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 1,
                'sku'            => 'FLT-2204',
                'barcode'        => '8690001122044',
                'name'           => 'Hidrolik Filtre',
                'stock_quantity' => 30,
                'store_stock'    => 7,
                'minimum_stock'  => 5,
                'purchase_price' => 95.00,
                'sale_price'     => 160.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // Fren (category_id = 2) — 4 yeni ürün
            [
                'category_id'    => 2,
                'sku'            => 'FRN-2201',
                'barcode'        => '8690002122011',
                'name'           => 'El Freni Kablosu',
                'stock_quantity' => 25,
                'store_stock'    => 6,
                'minimum_stock'  => 4,
                'purchase_price' => 130.00,
                'sale_price'     => 220.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 2,
                'sku'            => 'FRN-2202',
                'barcode'        => '8690002122022',
                'name'           => 'Fren Kaliperi Ön',
                'stock_quantity' => 18,
                'store_stock'    => 4,
                'minimum_stock'  => 3,
                'purchase_price' => 480.00,
                'sale_price'     => 799.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 2,
                'sku'            => 'FRN-2203',
                'barcode'        => '8690002122033',
                'name'           => 'Fren Diski Arka Çift',
                'stock_quantity' => 22,
                'store_stock'    => 5,
                'minimum_stock'  => 3,
                'purchase_price' => 350.00,
                'sale_price'     => 590.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 2,
                'sku'            => 'FRN-2204',
                'barcode'        => '8690002122044',
                'name'           => 'Fren Ana Silindiri',
                'stock_quantity' => 14,
                'store_stock'    => 3,
                'minimum_stock'  => 3,
                'purchase_price' => 560.00,
                'sale_price'     => 950.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // Elektrik (category_id = 3) — 4 yeni ürün
            [
                'category_id'    => 3,
                'sku'            => 'ELK-2201',
                'barcode'        => '8690003122011',
                'name'           => 'Far Ampulü H7 Çift',
                'stock_quantity' => 60,
                'store_stock'    => 15,
                'minimum_stock'  => 10,
                'purchase_price' => 45.00,
                'sale_price'     => 79.00,
                'is_favorite'    => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 3,
                'sku'            => 'ELK-2202',
                'barcode'        => '8690003122022',
                'name'           => 'Marş Motoru',
                'stock_quantity' => 12,
                'store_stock'    => 3,
                'minimum_stock'  => 2,
                'purchase_price' => 920.00,
                'sale_price'     => 1550.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 3,
                'sku'            => 'ELK-2203',
                'barcode'        => '8690003122033',
                'name'           => 'Krank Sensörü',
                'stock_quantity' => 28,
                'store_stock'    => 6,
                'minimum_stock'  => 4,
                'purchase_price' => 185.00,
                'sale_price'     => 310.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 3,
                'sku'            => 'ELK-2204',
                'barcode'        => '8690003122044',
                'name'           => 'Lambda Sensörü',
                'stock_quantity' => 24,
                'store_stock'    => 5,
                'minimum_stock'  => 4,
                'purchase_price' => 340.00,
                'sale_price'     => 570.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // Şanzıman (category_id = 4) — 4 yeni ürün
            [
                'category_id'    => 4,
                'sku'            => 'SNZ-2201',
                'barcode'        => '8690004122011',
                'name'           => 'Şanzıman Yağı 75W90 1L',
                'stock_quantity' => 50,
                'store_stock'    => 12,
                'minimum_stock'  => 8,
                'purchase_price' => 120.00,
                'sale_price'     => 200.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 4,
                'sku'            => 'SNZ-2202',
                'barcode'        => '8690004122022',
                'name'           => 'Şaft Kafası İç',
                'stock_quantity' => 16,
                'store_stock'    => 4,
                'minimum_stock'  => 3,
                'purchase_price' => 650.00,
                'sale_price'     => 1090.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 4,
                'sku'            => 'SNZ-2203',
                'barcode'        => '8690004122033',
                'name'           => 'Şaft Kafası Dış',
                'stock_quantity' => 16,
                'store_stock'    => 4,
                'minimum_stock'  => 3,
                'purchase_price' => 580.00,
                'sale_price'     => 980.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 4,
                'sku'            => 'SNZ-2204',
                'barcode'        => '8690004122044',
                'name'           => 'Diferansiyel Yatağı',
                'stock_quantity' => 20,
                'store_stock'    => 5,
                'minimum_stock'  => 3,
                'purchase_price' => 280.00,
                'sale_price'     => 470.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // Motor (category_id = 5) — 4 yeni ürün
            [
                'category_id'    => 5,
                'sku'            => 'MTR-2201',
                'barcode'        => '8690005122011',
                'name'           => 'Motor Yağı 5W40 4L',
                'stock_quantity' => 80,
                'store_stock'    => 20,
                'minimum_stock'  => 15,
                'purchase_price' => 280.00,
                'sale_price'     => 450.00,
                'is_favorite'    => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 5,
                'sku'            => 'MTR-2202',
                'barcode'        => '8690005122022',
                'name'           => 'Termosta Valfi',
                'stock_quantity' => 22,
                'store_stock'    => 5,
                'minimum_stock'  => 4,
                'purchase_price' => 175.00,
                'sale_price'     => 295.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 5,
                'sku'            => 'MTR-2203',
                'barcode'        => '8690005122033',
                'name'           => 'Su Pompası',
                'stock_quantity' => 18,
                'store_stock'    => 4,
                'minimum_stock'  => 3,
                'purchase_price' => 420.00,
                'sale_price'     => 710.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 5,
                'sku'            => 'MTR-2204',
                'barcode'        => '8690005122044',
                'name'           => 'Eksoz Manifoldu Contası',
                'stock_quantity' => 35,
                'store_stock'    => 8,
                'minimum_stock'  => 5,
                'purchase_price' => 65.00,
                'sale_price'     => 110.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],

            // Diğer (category_id = 6) — 3 yeni ürün
            [
                'category_id'    => 6,
                'sku'            => 'DGR-2201',
                'barcode'        => '8690006122011',
                'name'           => 'Silecek Süpürgesi 60cm',
                'stock_quantity' => 55,
                'store_stock'    => 14,
                'minimum_stock'  => 10,
                'purchase_price' => 55.00,
                'sale_price'     => 95.00,
                'is_favorite'    => 1,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 6,
                'sku'            => 'DGR-2202',
                'barcode'        => '8690006122022',
                'name'           => 'Radyatör Antifriz 1L',
                'stock_quantity' => 70,
                'store_stock'    => 18,
                'minimum_stock'  => 12,
                'purchase_price' => 75.00,
                'sale_price'     => 125.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
            [
                'category_id'    => 6,
                'sku'            => 'DGR-2203',
                'barcode'        => '8690006122033',
                'name'           => 'Direksiyon Körüğü Takımı',
                'stock_quantity' => 14,
                'store_stock'    => 3,
                'minimum_stock'  => 3,
                'purchase_price' => 310.00,
                'sale_price'     => 525.00,
                'is_favorite'    => 0,
                'created_at'     => $now,
                'updated_at'     => $now,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
